#!/usr/bin/env bash
set -e
if [[ $# -eq 0 ]]; then
    echo "Usage: ./orderly_install instance_name 'command'
    instance_name - fertility or naomi
    command - The remotes::install_github or install_packages command, remember the quotes"
    exit 1
fi

INSTANCE=$1
shift
CONTAINERS=`docker ps --filter name=${INSTANCE}_orderly* --filter status=running -aq`
CONTAINER_NAMES=`docker ps --filter name=${INSTANCE}_orderly* --filter status=running --format '{{.Names}}' -a | paste -sd '~ ' | sed 's/~/, /'`
echo "Running Rscript in containers ${CONTAINER_NAMES}"

for CONTAINER in $CONTAINERS
do
    docker exec $CONTAINER Rscript -e $@
done

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'
echo "
"
echo "Installation complete"
echo -e "${CYAN}ʕಠᴥಠʔ ${YELLOW}ಠ_ಠ ${GREEN}ᶘಠᴥಠᶅ ${RED}VERY IMPORTANT ${GREEN}ʕಠᴥಠʔ ${YELLOW}ಠ_ಠ ${CYAN}ᶘಠᴥಠᶅ${NC}"
echo "Update Dockerfile so the package is available after a redeploy"