#!/usr/bin/env bash
set -e

usage="Start all or specific orderly web instances
Usage: $(basename "$0") [-h] (all | <configname>...)

Options:
    -h  Show this help text"

while getopts 'h' option; do
  case "$option" in
  h)
    echo "$usage"
    exit 0
    ;;
  esac
done

function start_ow {
  orderly-web start $1 --pull
}

for var in "$@"; do
  if [ $var == "all" ]; then
    ## List all config directories i.e. all directories except "scripts"
    configs = $(find * -type d | egrep -v '^scripts/|/scripts/|scripts')
    for conf in $configs; do
      start_ow $conf
    done
  else
    start_ow $var
  fi
done
