#!/usr/bin/env bash
set -e

usage="Start all or specific orderly web instances
Usage: $(basename "$0") [-h] (all | <configname>...)

Options:
    -h  Show this help text"

if [[ -z "$@" ]]; then
    echo "$USAGE"
    exit 1
fi
OPTIONS=$(getopt -o h -- "$@")

eval set -- "$OPTIONS"
while true; do
    case "$1" in
    -h)
        echo "$USAGE"
        exit 0
        ;;
    --)
        shift
        break
        ;;
    esac
done

function start_ow {
  orderly-web start $1 --pull
}

for var in "$@"; do
  if [ $var == "all" ]; then
    ## List all config directories i.e. all directories except "scripts"
    configs=$(find * -type d | egrep -v '^scripts/|/scripts/|scripts')
    for conf in $configs; do
      start_ow $conf
    done
  else
    start_ow $var
  fi
done
