#!/usr/bin/env bash

USAGE="Stop all or specific orderly web instances
Usage: $(basename "$0") [-h] [--kill] (all | <configname>...)

Options:
    -h      Show this help text
    --kill  Kill the containers (faster, but possible db corruption)"

if [[ -z "$@" ]]; then
    echo "$USAGE"
    exit 1
fi
OPTIONS=$(getopt -o h --long kill -- "$@")

eval set -- "$OPTIONS"
while true; do
    case "$1" in
    -h)
        echo "$USAGE"
        exit 0
        ;;
    --kill)
        KILL="--kill"
        shift
        ;;
    --)
        shift
        break
        ;;
    esac
done

function stop_ow {
  orderly-web stop $1 $KILL
}

for var in "$@"; do
  if [ $var == "all" ]; then
    ## List all config directories i.e. all directories except "scripts"
    configs=`find * -type d | egrep -v '^scripts/|/scripts/|scripts'`
    for conf in $configs; do
      stop_ow $conf
    done
  else
    stop_ow $var
  fi
done
