#!/usr/bin/env bash
set -e

usage="Stop all or specific orderly web instances
Usage: $(basename "$0") [-h] (all | <configname>...)

Options:
    -h  Show this help text"

while getopts 'h' option; do
  case "$option" in
  h)
    echo "$usage"
    exit 0
    ;;
  esac
done

function stop_ow {
  orderly-web stop $1
}

for var in "$@"; do
  if [ $var == "all" ]; then
    ## List all config directories i.e. all directories except "scripts"
    configs = `find * -type d | egrep -v '^scripts/|/scripts/|scripts'`
    for conf in $configs; do
      stop_ow $conf
    done
  else
    stop_ow $var
  fi
done
